### ISSUE TITLE
Contributors Section

### ISSUE THREAD

**Issue by alejandro-sg** [GersonLazaro/learn-x-if-you-know-y#28]
Hi @GersonLazaro,

I have an idea/suggestion, to get rid of the bullet points for the list item on the contributors section.
I have forked the project and made the changes locally in my computer. I added default Boostrap classes. I have a included a couple of screen shots, so you can see what I'm talking about.
![after](https://user-images.githubusercontent.com/8007671/31752308-253b0518-b458-11e7-9b16-5e3766600dc7.png)
![before](https://user-images.githubusercontent.com/8007671/31752309-254830c6-b458-11e7-8799-d356032b5bd6.png)

Let me know what you think, thank you!

**Comment by GersonLazaro** [comment]
Hi @juan-sierra .
I also wanted to get rid of the bullet points :laughing: . Send the pull request, your version looks much better.

Thank you

**Comment by alejandro-sg** [comment]
Hello @GersonLazaro thank you for letting me contribute. I sent the pull request let me if there any issues! #45

**Comment by GersonLazaro** [comment]
Thanks!
:1st_place_medal:
