### ISSUE TITLE
Help Wanted #Hacktoberfest

### ISSUE THREAD

**Issue by GersonLazaro** [GersonLazaro/learn-x-if-you-know-y#5]
> "Do you know some programming language? Are you learning a new one? Learn language X by comparing its instructions with their equivalent in language Y. Just select the language X which you want to learn about, the language Y that you already know, and start to learn!"

Do you want to collaborate? You are welcome. It's easy and fast (Just read the contributing.md).

What is hacktoberfest? You can read [this](hacktoberfest.digitalocean.com/).

**Comment by raheemazeezabiodun** [comment]
Hi,

I want to write for loop in python. should i go for it?

**Comment by GersonLazaro** [comment]
@raheemazeezabiodun Yes. You can do it (thank you very much)

**Comment by brunopulis** [comment]
I want to write foreach loop in Javascript, should I go for it?

**Comment by thecoderkd** [comment]
I have added Kotlin examples. Hope you like it.
Feel free to message if you want some more examples in kotlin. Happy Hacktoberfest
:)

**Comment by thecoderkd** [comment]
Hey @GersonLazaro I did not knew that we only had to add to the already set languages. But I think that you should also add Kotlin to your set of languages because Kotlin is now picking up some serious heat after this year's Google I/O. Hope you like it. .

**Comment by GersonLazaro** [comment]
@thecoderkd you can also add new languages, thanks for the contribution in kotlin (Curiosity: I am currently learning kotlin). :clap:

**Comment by kuper-adrian** [comment]
Will add examples for C#, if that is ok

**Comment by thecoderkd** [comment]
@GersonLazaro yeah me too buddy. Just started learning and saw your project :)

**Comment by ankushgarg1998** [comment]
Hey,
Can I add Dynamic Arrays in C and C++ ?

**Comment by Paarmita** [comment]
I am a beginner in js could i also contribute with some initial code
